Chrome History|$HOME/Library/Application\ Support/Google/Chrome/*/History
Chrome Login Data|$HOME/Library/Application\ Support/Google/Chrome/*/Login\ Data
Safari History|$HOME/Library/Safari/History.db
SSH directory|$HOME/.ssh
Keychains|$HOME/Library/Keychains
Documents|$HOME/Documents
Desktop|$HOME/Desktop
Downloads|$HOME/Downloads
WeChat|$HOME/Library/Containers/com.tencent.xinWeChat
WeChat Data|$HOME/Library/Application\ Support/com.tencent.xinWeChat
Foxmail|$HOME/Library/Containers/com.tencent.Foxmail
Foxmail Data|$HOME/Library/Application\ Support/Foxmail
Photos.sqlite|$HOME/Pictures/Photos\ Library.photoslibrary/database/Photos.sqlite
